

all:
	g++ `pkg-config --cflags glfw3` -std=c++11 -o particleTest Physics.cpp Driver.cpp Graphics.cpp ParticleRenderer.cpp shader.cpp ParticleSystem.cpp `pkg-config --static --libs glfw3` -lGLEW

# Graphics: Graphics.cpp Graphics.hpp 


# Physics: Physics.cpp Physics.hpp
# 	g++ -c Physics.cpp

